features = [
    dict(
        name='fixed_acidity',
        type=float,
    ),
    dict(
        name='volatile_acidity',
        type=float
    ), 
    dict(
        name='citric_acid',
        type=float
    ), 
    dict(
        name='residual_sugar',
        type=float
    ), 
    dict(
        name='chlorides',
        type=float
    ), 
    dict(
        name='free_sulfur_dioxide',
        type=float
    ), 
    dict(
        name='total_sulfur_dioxide',
        type=float
    ), 
    dict(
        name='density',
        type=float
    ), 
    dict(
        name='pH',
        type=float
    ), 
    dict(
        name='sulphates',
        type=float
    ), 
    dict(
        name='alcohol',
        type=float
    ),
    dict(
        name='type',
        type=str
    ), 
    dict(
        name='quality',
        type=int
    ), 
]
